In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('credit_risk_dataset.csv')
data

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

In [ ]:
df = data.copy() 
# rename columns to be more readable 
df = df.rename(columns={'person_age': 'age', 
                          'person_income': 'income',
                          'person_home_ownership': 'home_ownership',
                          'person_emp_length': 'emp_length',
                          'cb_person_default_on_file': 'default_on_file',
                          'cb_person_cred_hist_length': 'cred_hist_length'})

# only keep rows where age is between 20 and 34 to classify as 'young adults'
df = df[(df["age"] >= 20) & (df["age"] <= 34)]
df

,age,income,home_ownership,emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,default_on_file,cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
29114,31,83000,MORTGAGE,9.0,VENTURE,F,18000,19.74,1,0.22,Y,8
29115,29,61656,RENT,4.0,PERSONAL,A,15000,6.91,0,0.24,N,9
29116,32,30000,RENT,1.0,EDUCATION,B,11450,9.99,1,0.38,N,6
29117,31,26010,MORTGAGE,2.0,PERSONAL,B,6500,9.99,0,0.25,N,9
29118,30,52000,MORTGAGE,4.0,HOMEIMPROVEMENT,B,14675,9.63,0,0.28,N,7

In [ ]:
# one hot encode person_home_ownership and drop original column
df2 = df.copy() 
df2 = pd.get_dummies(df, columns=['home_ownership', 'loan_intent'], dtype=int)

# map loan grade to numerical values 
grade_map = {'A': 1, 'B': 2, 'C': 3, 'D': 4, 'E': 5, 'F': 6, 'G': 7}
df2['loan_grade'] = df2['loan_grade'].map(grade_map)

# map previous default to 1 for yes and 0 for no
df2['default_on_file'] = df2['default_on_file'].map({'Y': 1, 'N': 0})
df2

In [ ]:
# save cleaned dataset to csv
df2.to_csv('cleaned_credit_risk_dataset.csv', index=False)